
version: "3.8"
services:
  # NLP - Node Server
  nlp-node:
    build:
      context: "./nlp-node/"
    ports:
      - "5000:5000"
    volumes:
      - "./logs:/usr/src/app/logs"
      - "./nlp-node/resource:/usr/src/app/resource"
  # NLP - Flask Server
  nlp-flask:
    build:
      context: "./nlp-flask/"
    ports:
      - "30080:30080"
